{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "sdk",
    "version": "0.3.0-test-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-test-1.aar",
          "url": "sdk-0.3.0-test-1.aar",
          "size": 108205,
          "sha512": "3455e9686d03bb950c5703183094913383ac3dd6145b93d9e12a9874a0802fe63bbcbe9e1680bc8915b0f4dcfba363c5f7f43b5c32c1ccc210f0ab0bafff4b8d",
          "sha256": "b4dc7a9b9cf7dacfafe3018bd88f022b4d2cc7bf8f4c965c9ccc1712c10753e6",
          "sha1": "417a06281ee83a24df74d2e2c875fb6920076321",
          "md5": "71b351b6deb8e062ad2a9c8103cc403b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-0.3.0-test-1.aar",
          "url": "sdk-0.3.0-test-1.aar",
          "size": 108205,
          "sha512": "3455e9686d03bb950c5703183094913383ac3dd6145b93d9e12a9874a0802fe63bbcbe9e1680bc8915b0f4dcfba363c5f7f43b5c32c1ccc210f0ab0bafff4b8d",
          "sha256": "b4dc7a9b9cf7dacfafe3018bd88f022b4d2cc7bf8f4c965c9ccc1712c10753e6",
          "sha1": "417a06281ee83a24df74d2e2c875fb6920076321",
          "md5": "71b351b6deb8e062ad2a9c8103cc403b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-0.3.0-test-1-sources.jar",
          "url": "sdk-0.3.0-test-1-sources.jar",
          "size": 26249,
          "sha512": "c3e2b32e81909571ab9d7d35e8cb0acea8c9c90d31e05c733e393dcd3b4f97f5461743839f58cd7383c26e5aa8985300a066af59908de36e7166886be1509eef",
          "sha256": "40d0c6af0aad3ff8dc8a9ae4e726de405fc7c5a0e7cc5637a051a21983b14529",
          "sha1": "75a5e9f1cb6bc66592af63e6aef0123906bf3ebc",
          "md5": "7963ba32ed8db144223fc7d173f4921d"
        }
      ]
    }
  ]
}
